/**
 * N4 Vocabulary Data - Essential N4 vocabulary for JLPT preparation
 * Referenced from JLPT Sensei and Genki II textbook materials
 * Building on N5's vocabulary with additional N4 vocabulary
 */

export const n4VocabularyData = [
    // ==================== Verbs - Transitive/Intransitive Pairs ====================
    { writing: '開ける', reading: 'あける', meaning: 'to open (transitive)', partOfSpeech: 'verb' },
    { writing: '開く', reading: 'あく', meaning: 'to open (intransitive)', partOfSpeech: 'verb' },
    { writing: '閉める', reading: 'しめる', meaning: 'to close (transitive)', partOfSpeech: 'verb' },
    { writing: '閉まる', reading: 'しまる', meaning: 'to close (intransitive)', partOfSpeech: 'verb' },
    { writing: '付ける', reading: 'つける', meaning: 'to attach, to turn on (transitive)', partOfSpeech: 'verb' },
    { writing: '付く', reading: 'つく', meaning: 'to be attached, to turn on (intransitive)', partOfSpeech: 'verb' },
    { writing: '消す', reading: 'けす', meaning: 'to erase, to turn off (transitive)', partOfSpeech: 'verb' },
    { writing: '消える', reading: 'きえる', meaning: 'to disappear, to go off (intransitive)', partOfSpeech: 'verb' },
    { writing: '始める', reading: 'はじめる', meaning: 'to begin (transitive)', partOfSpeech: 'verb' },
    { writing: '始まる', reading: 'はじまる', meaning: 'to begin (intransitive)', partOfSpeech: 'verb' },
    { writing: '終える', reading: 'おえる', meaning: 'to finish (transitive)', partOfSpeech: 'verb' },
    { writing: '終わる', reading: 'おわる', meaning: 'to end (intransitive)', partOfSpeech: 'verb' },
    { writing: '入れる', reading: 'いれる', meaning: 'to put in (transitive)', partOfSpeech: 'verb' },
    { writing: '入る', reading: 'はいる', meaning: 'to enter (intransitive)', partOfSpeech: 'verb' },
    { writing: '出す', reading: 'だす', meaning: 'to take out (transitive)', partOfSpeech: 'verb' },
    { writing: '出る', reading: 'でる', meaning: 'to go out (intransitive)', partOfSpeech: 'verb' },
    { writing: '落とす', reading: 'おとす', meaning: 'to drop (transitive)', partOfSpeech: 'verb' },
    { writing: '落ちる', reading: 'おちる', meaning: 'to fall (intransitive)', partOfSpeech: 'verb' },
    { writing: '壊す', reading: 'こわす', meaning: 'to break (transitive)', partOfSpeech: 'verb' },
    { writing: '壊れる', reading: 'こわれる', meaning: 'to be broken (intransitive)', partOfSpeech: 'verb' },
    { writing: '直す', reading: 'なおす', meaning: 'to fix, to correct (transitive)', partOfSpeech: 'verb' },
    { writing: '直る', reading: 'なおる', meaning: 'to be fixed (intransitive)', partOfSpeech: 'verb' },
    { writing: '集める', reading: 'あつめる', meaning: 'to collect (transitive)', partOfSpeech: 'verb' },
    { writing: '集まる', reading: 'あつまる', meaning: 'to gather (intransitive)', partOfSpeech: 'verb' },
    { writing: '届ける', reading: 'とどける', meaning: 'to deliver (transitive)', partOfSpeech: 'verb' },
    { writing: '届く', reading: 'とどく', meaning: 'to reach, to arrive (intransitive)', partOfSpeech: 'verb' },
    { writing: '見つける', reading: 'みつける', meaning: 'to find (transitive)', partOfSpeech: 'verb' },
    { writing: '見つかる', reading: 'みつかる', meaning: 'to be found (intransitive)', partOfSpeech: 'verb' },
    { writing: '決める', reading: 'きめる', meaning: 'to decide (transitive)', partOfSpeech: 'verb' },
    { writing: '決まる', reading: 'きまる', meaning: 'to be decided (intransitive)', partOfSpeech: 'verb' },
    { writing: '変える', reading: 'かえる', meaning: 'to change (transitive)', partOfSpeech: 'verb' },
    { writing: '変わる', reading: 'かわる', meaning: 'to change (intransitive)', partOfSpeech: 'verb' },
    { writing: '上げる', reading: 'あげる', meaning: 'to raise (transitive)', partOfSpeech: 'verb' },
    { writing: '上がる', reading: 'あがる', meaning: 'to rise (intransitive)', partOfSpeech: 'verb' },
    { writing: '下げる', reading: 'さげる', meaning: 'to lower (transitive)', partOfSpeech: 'verb' },
    { writing: '下がる', reading: 'さがる', meaning: 'to go down (intransitive)', partOfSpeech: 'verb' },

    // ==================== Common N4 Verbs ====================
    { writing: '送る', reading: 'おくる', meaning: 'to send', partOfSpeech: 'verb' },
    { writing: '届く', reading: 'とどく', meaning: 'to arrive', partOfSpeech: 'verb' },
    { writing: '届ける', reading: 'とどける', meaning: 'to deliver', partOfSpeech: 'verb' },
    { writing: '運ぶ', reading: 'はこぶ', meaning: 'to carry, to transport', partOfSpeech: 'verb' },
    { writing: '動く', reading: 'うごく', meaning: 'to move', partOfSpeech: 'verb' },
    { writing: '止まる', reading: 'とまる', meaning: 'to stop', partOfSpeech: 'verb' },
    { writing: '止める', reading: 'とめる', meaning: 'to stop (something)', partOfSpeech: 'verb' },
    { writing: '待つ', reading: 'まつ', meaning: 'to wait', partOfSpeech: 'verb' },
    { writing: '遅れる', reading: 'おくれる', meaning: 'to be late', partOfSpeech: 'verb' },
    { writing: '急ぐ', reading: 'いそぐ', meaning: 'to hurry', partOfSpeech: 'verb' },
    { writing: '走る', reading: 'はしる', meaning: 'to run', partOfSpeech: 'verb' },
    { writing: '歩く', reading: 'あるく', meaning: 'to walk', partOfSpeech: 'verb' },
    { writing: '起きる', reading: 'おきる', meaning: 'to wake up, to get up', partOfSpeech: 'verb' },
    { writing: '寝る', reading: 'ねる', meaning: 'to sleep, to go to bed', partOfSpeech: 'verb' },
    { writing: '着る', reading: 'きる', meaning: 'to wear (upper body)', partOfSpeech: 'verb' },
    { writing: '脱ぐ', reading: 'ぬぐ', meaning: 'to take off (clothes)', partOfSpeech: 'verb' },
    { writing: '履く', reading: 'はく', meaning: 'to wear (lower body)', partOfSpeech: 'verb' },
    { writing: '被る', reading: 'かぶる', meaning: 'to wear (on head)', partOfSpeech: 'verb' },
    { writing: '掛ける', reading: 'かける', meaning: 'to hang, to call (phone)', partOfSpeech: 'verb' },
    { writing: '置く', reading: 'おく', meaning: 'to put, to place', partOfSpeech: 'verb' },
    { writing: '取る', reading: 'とる', meaning: 'to take, to get', partOfSpeech: 'verb' },
    { writing: '持つ', reading: 'もつ', meaning: 'to hold, to have', partOfSpeech: 'verb' },
    { writing: '渡す', reading: 'わたす', meaning: 'to hand over', partOfSpeech: 'verb' },
    { writing: '渡る', reading: 'わたる', meaning: 'to cross', partOfSpeech: 'verb' },
    { writing: '乗る', reading: 'のる', meaning: 'to ride, to get on', partOfSpeech: 'verb' },
    { writing: '降りる', reading: 'おりる', meaning: 'to get off, to descend', partOfSpeech: 'verb' },
    { writing: '乗り換える', reading: 'のりかえる', meaning: 'to transfer (vehicles)', partOfSpeech: 'verb' },
    { writing: '曲がる', reading: 'まがる', meaning: 'to turn, to bend', partOfSpeech: 'verb' },
    { writing: '進む', reading: 'すすむ', meaning: 'to advance, to proceed', partOfSpeech: 'verb' },
    { writing: '戻る', reading: 'もどる', meaning: 'to return, to go back', partOfSpeech: 'verb' },
    { writing: '帰る', reading: 'かえる', meaning: 'to return home', partOfSpeech: 'verb' },
    { writing: '出かける', reading: 'でかける', meaning: 'to go out', partOfSpeech: 'verb' },
    { writing: '通る', reading: 'とおる', meaning: 'to pass through', partOfSpeech: 'verb' },
    { writing: '通う', reading: 'かよう', meaning: 'to commute, to attend', partOfSpeech: 'verb' },

    // ==================== Mental/Communication Verbs ====================
    { writing: '思う', reading: 'おもう', meaning: 'to think', partOfSpeech: 'verb' },
    { writing: '考える', reading: 'かんがえる', meaning: 'to think, to consider', partOfSpeech: 'verb' },
    { writing: '知る', reading: 'しる', meaning: 'to know', partOfSpeech: 'verb' },
    { writing: '覚える', reading: 'おぼえる', meaning: 'to remember, to memorize', partOfSpeech: 'verb' },
    { writing: '忘れる', reading: 'わすれる', meaning: 'to forget', partOfSpeech: 'verb' },
    { writing: '思い出す', reading: 'おもいだす', meaning: 'to recall, to remember', partOfSpeech: 'verb' },
    { writing: '信じる', reading: 'しんじる', meaning: 'to believe', partOfSpeech: 'verb' },
    { writing: '間違える', reading: 'まちがえる', meaning: 'to make a mistake', partOfSpeech: 'verb' },
    { writing: '迷う', reading: 'まよう', meaning: 'to be lost, to hesitate', partOfSpeech: 'verb' },
    { writing: '調べる', reading: 'しらべる', meaning: 'to investigate, to look up', partOfSpeech: 'verb' },
    { writing: '比べる', reading: 'くらべる', meaning: 'to compare', partOfSpeech: 'verb' },
    { writing: '選ぶ', reading: 'えらぶ', meaning: 'to choose, to select', partOfSpeech: 'verb' },
    { writing: '伝える', reading: 'つたえる', meaning: 'to convey, to tell', partOfSpeech: 'verb' },
    { writing: '説明する', reading: 'せつめいする', meaning: 'to explain', partOfSpeech: 'verb' },
    { writing: '紹介する', reading: 'しょうかいする', meaning: 'to introduce', partOfSpeech: 'verb' },
    { writing: '案内する', reading: 'あんないする', meaning: 'to guide', partOfSpeech: 'verb' },
    { writing: '謝る', reading: 'あやまる', meaning: 'to apologize', partOfSpeech: 'verb' },
    { writing: '褒める', reading: 'ほめる', meaning: 'to praise', partOfSpeech: 'verb' },
    { writing: '叱る', reading: 'しかる', meaning: 'to scold', partOfSpeech: 'verb' },
    { writing: '驚く', reading: 'おどろく', meaning: 'to be surprised', partOfSpeech: 'verb' },
    { writing: '喜ぶ', reading: 'よろこぶ', meaning: 'to be glad', partOfSpeech: 'verb' },
    { writing: '悲しむ', reading: 'かなしむ', meaning: 'to be sad', partOfSpeech: 'verb' },
    { writing: '怒る', reading: 'おこる', meaning: 'to get angry', partOfSpeech: 'verb' },
    { writing: '困る', reading: 'こまる', meaning: 'to be troubled', partOfSpeech: 'verb' },
    { writing: '心配する', reading: 'しんぱいする', meaning: 'to worry', partOfSpeech: 'verb' },
    { writing: '安心する', reading: 'あんしんする', meaning: 'to be relieved', partOfSpeech: 'verb' },

    // ==================== Daily Life Verbs ====================
    { writing: '作る', reading: 'つくる', meaning: 'to make, to create', partOfSpeech: 'verb' },
    { writing: '使う', reading: 'つかう', meaning: 'to use', partOfSpeech: 'verb' },
    { writing: '片付ける', reading: 'かたづける', meaning: 'to tidy up', partOfSpeech: 'verb' },
    { writing: '掃除する', reading: 'そうじする', meaning: 'to clean', partOfSpeech: 'verb' },
    { writing: '洗濯する', reading: 'せんたくする', meaning: 'to do laundry', partOfSpeech: 'verb' },
    { writing: '料理する', reading: 'りょうりする', meaning: 'to cook', partOfSpeech: 'verb' },
    { writing: '焼く', reading: 'やく', meaning: 'to grill, to bake', partOfSpeech: 'verb' },
    { writing: '煮る', reading: 'にる', meaning: 'to boil, to simmer', partOfSpeech: 'verb' },
    { writing: '沸かす', reading: 'わかす', meaning: 'to boil (water)', partOfSpeech: 'verb' },
    { writing: '沸く', reading: 'わく', meaning: 'to boil (intransitive)', partOfSpeech: 'verb' },
    { writing: '切る', reading: 'きる', meaning: 'to cut', partOfSpeech: 'verb' },
    { writing: '磨く', reading: 'みがく', meaning: 'to polish, to brush', partOfSpeech: 'verb' },
    { writing: '洗う', reading: 'あらう', meaning: 'to wash', partOfSpeech: 'verb' },
    { writing: '乾く', reading: 'かわく', meaning: 'to dry', partOfSpeech: 'verb' },
    { writing: '乾かす', reading: 'かわかす', meaning: 'to dry (transitive)', partOfSpeech: 'verb' },
    { writing: '買い物する', reading: 'かいものする', meaning: 'to shop', partOfSpeech: 'verb' },
    { writing: '探す', reading: 'さがす', meaning: 'to search for', partOfSpeech: 'verb' },
    { writing: '返す', reading: 'かえす', meaning: 'to return (something)', partOfSpeech: 'verb' },
    { writing: '借りる', reading: 'かりる', meaning: 'to borrow', partOfSpeech: 'verb' },
    { writing: '貸す', reading: 'かす', meaning: 'to lend', partOfSpeech: 'verb' },
    { writing: '払う', reading: 'はらう', meaning: 'to pay', partOfSpeech: 'verb' },
    { writing: '受け取る', reading: 'うけとる', meaning: 'to receive', partOfSpeech: 'verb' },

    // ==================== Learning/Work Verbs ====================
    { writing: '習う', reading: 'ならう', meaning: 'to learn', partOfSpeech: 'verb' },
    { writing: '教える', reading: 'おしえる', meaning: 'to teach, to tell', partOfSpeech: 'verb' },
    { writing: '勉強する', reading: 'べんきょうする', meaning: 'to study', partOfSpeech: 'verb' },
    { writing: '練習する', reading: 'れんしゅうする', meaning: 'to practice', partOfSpeech: 'verb' },
    { writing: '復習する', reading: 'ふくしゅうする', meaning: 'to review', partOfSpeech: 'verb' },
    { writing: '予習する', reading: 'よしゅうする', meaning: 'to prepare lessons', partOfSpeech: 'verb' },
    { writing: '試験を受ける', reading: 'しけんをうける', meaning: 'to take an exam', partOfSpeech: 'expression' },
    { writing: '卒業する', reading: 'そつぎょうする', meaning: 'to graduate', partOfSpeech: 'verb' },
    { writing: '入学する', reading: 'にゅうがくする', meaning: 'to enter school', partOfSpeech: 'verb' },
    { writing: '就職する', reading: 'しゅうしょくする', meaning: 'to get a job', partOfSpeech: 'verb' },
    { writing: '働く', reading: 'はたらく', meaning: 'to work', partOfSpeech: 'verb' },
    { writing: '辞める', reading: 'やめる', meaning: 'to quit', partOfSpeech: 'verb' },
    { writing: '続ける', reading: 'つづける', meaning: 'to continue', partOfSpeech: 'verb' },
    { writing: '続く', reading: 'つづく', meaning: 'to continue (intransitive)', partOfSpeech: 'verb' },

    // ==================== Nouns - People ====================
    { writing: '赤ちゃん', reading: 'あかちゃん', meaning: 'baby', partOfSpeech: 'noun' },
    { writing: '子供', reading: 'こども', meaning: 'child', partOfSpeech: 'noun' },
    { writing: '大人', reading: 'おとな', meaning: 'adult', partOfSpeech: 'noun' },
    { writing: '若者', reading: 'わかもの', meaning: 'young person', partOfSpeech: 'noun' },
    { writing: 'お年寄り', reading: 'おとしより', meaning: 'elderly person', partOfSpeech: 'noun' },
    { writing: '彼', reading: 'かれ', meaning: 'he, boyfriend', partOfSpeech: 'noun' },
    { writing: '彼女', reading: 'かのじょ', meaning: 'she, girlfriend', partOfSpeech: 'noun' },
    { writing: '彼ら', reading: 'かれら', meaning: 'they (male/mixed)', partOfSpeech: 'noun' },
    { writing: '僕', reading: 'ぼく', meaning: 'I (male, casual)', partOfSpeech: 'noun' },
    { writing: '君', reading: 'きみ', meaning: 'you (casual)', partOfSpeech: 'noun' },
    { writing: '自分', reading: 'じぶん', meaning: 'oneself', partOfSpeech: 'noun' },
    { writing: '皆', reading: 'みな', meaning: 'everyone', partOfSpeech: 'noun' },
    { writing: '皆さん', reading: 'みなさん', meaning: 'everyone (polite)', partOfSpeech: 'noun' },
    { writing: '客', reading: 'きゃく', meaning: 'guest, customer', partOfSpeech: 'noun' },
    { writing: 'お客さん', reading: 'おきゃくさん', meaning: 'guest, customer (polite)', partOfSpeech: 'noun' },
    { writing: '男性', reading: 'だんせい', meaning: 'male, man', partOfSpeech: 'noun' },
    { writing: '女性', reading: 'じょせい', meaning: 'female, woman', partOfSpeech: 'noun' },
    { writing: '友人', reading: 'ゆうじん', meaning: 'friend (formal)', partOfSpeech: 'noun' },
    { writing: '知り合い', reading: 'しりあい', meaning: 'acquaintance', partOfSpeech: 'noun' },
    { writing: '親戚', reading: 'しんせき', meaning: 'relative', partOfSpeech: 'noun' },
    { writing: '隣人', reading: 'りんじん', meaning: 'neighbor', partOfSpeech: 'noun' },

    // ==================== Nouns - Places ====================
    { writing: '場所', reading: 'ばしょ', meaning: 'place, location', partOfSpeech: 'noun' },
    { writing: '住所', reading: 'じゅうしょ', meaning: 'address', partOfSpeech: 'noun' },
    { writing: '地図', reading: 'ちず', meaning: 'map', partOfSpeech: 'noun' },
    { writing: '地下', reading: 'ちか', meaning: 'underground, basement', partOfSpeech: 'noun' },
    { writing: '地下鉄', reading: 'ちかてつ', meaning: 'subway', partOfSpeech: 'noun' },
    { writing: '駐車場', reading: 'ちゅうしゃじょう', meaning: 'parking lot', partOfSpeech: 'noun' },
    { writing: '交差点', reading: 'こうさてん', meaning: 'intersection', partOfSpeech: 'noun' },
    { writing: '信号', reading: 'しんごう', meaning: 'traffic light', partOfSpeech: 'noun' },
    { writing: '角', reading: 'かど', meaning: 'corner', partOfSpeech: 'noun' },
    { writing: '道', reading: 'みち', meaning: 'road, way', partOfSpeech: 'noun' },
    { writing: '橋', reading: 'はし', meaning: 'bridge', partOfSpeech: 'noun' },
    { writing: '坂', reading: 'さか', meaning: 'slope, hill', partOfSpeech: 'noun' },
    { writing: '階段', reading: 'かいだん', meaning: 'stairs', partOfSpeech: 'noun' },
    { writing: 'エレベーター', reading: 'エレベーター', meaning: 'elevator', partOfSpeech: 'noun' },
    { writing: 'エスカレーター', reading: 'エスカレーター', meaning: 'escalator', partOfSpeech: 'noun' },
    { writing: '入り口', reading: 'いりぐち', meaning: 'entrance', partOfSpeech: 'noun' },
    { writing: '出口', reading: 'でぐち', meaning: 'exit', partOfSpeech: 'noun' },
    { writing: '受付', reading: 'うけつけ', meaning: 'reception', partOfSpeech: 'noun' },
    { writing: '美術館', reading: 'びじゅつかん', meaning: 'art museum', partOfSpeech: 'noun' },
    { writing: '動物園', reading: 'どうぶつえん', meaning: 'zoo', partOfSpeech: 'noun' },
    { writing: '遊園地', reading: 'ゆうえんち', meaning: 'amusement park', partOfSpeech: 'noun' },
    { writing: '神社', reading: 'じんじゃ', meaning: 'Shinto shrine', partOfSpeech: 'noun' },
    { writing: 'お寺', reading: 'おてら', meaning: 'Buddhist temple', partOfSpeech: 'noun' },
    { writing: '教会', reading: 'きょうかい', meaning: 'church', partOfSpeech: 'noun' },

    // ==================== Nouns - Time ====================
    { writing: '今度', reading: 'こんど', meaning: 'this time, next time', partOfSpeech: 'noun' },
    { writing: '今回', reading: 'こんかい', meaning: 'this time', partOfSpeech: 'noun' },
    { writing: '次回', reading: 'じかい', meaning: 'next time', partOfSpeech: 'noun' },
    { writing: '最近', reading: 'さいきん', meaning: 'recently', partOfSpeech: 'noun' },
    { writing: '将来', reading: 'しょうらい', meaning: 'future', partOfSpeech: 'noun' },
    { writing: '過去', reading: 'かこ', meaning: 'past', partOfSpeech: 'noun' },
    { writing: '現在', reading: 'げんざい', meaning: 'present, now', partOfSpeech: 'noun' },
    { writing: '時代', reading: 'じだい', meaning: 'era, period', partOfSpeech: 'noun' },
    { writing: '季節', reading: 'きせつ', meaning: 'season', partOfSpeech: 'noun' },
    { writing: '久しぶり', reading: 'ひさしぶり', meaning: 'long time no see', partOfSpeech: 'noun' },
    { writing: '急に', reading: 'きゅうに', meaning: 'suddenly', partOfSpeech: 'adverb' },
    { writing: 'ずっと', reading: 'ずっと', meaning: 'continuously, much more', partOfSpeech: 'adverb' },
    { writing: 'やっと', reading: 'やっと', meaning: 'finally, at last', partOfSpeech: 'adverb' },
    { writing: 'そろそろ', reading: 'そろそろ', meaning: 'soon, about time', partOfSpeech: 'adverb' },

    // ==================== Nouns - Things ====================
    { writing: '荷物', reading: 'にもつ', meaning: 'luggage, baggage', partOfSpeech: 'noun' },
    { writing: '手紙', reading: 'てがみ', meaning: 'letter', partOfSpeech: 'noun' },
    { writing: '葉書', reading: 'はがき', meaning: 'postcard', partOfSpeech: 'noun' },
    { writing: '封筒', reading: 'ふうとう', meaning: 'envelope', partOfSpeech: 'noun' },
    { writing: '切手', reading: 'きって', meaning: 'stamp', partOfSpeech: 'noun' },
    { writing: '小包', reading: 'こづつみ', meaning: 'package', partOfSpeech: 'noun' },
    { writing: '贈り物', reading: 'おくりもの', meaning: 'gift', partOfSpeech: 'noun' },
    { writing: 'お土産', reading: 'おみやげ', meaning: 'souvenir', partOfSpeech: 'noun' },
    { writing: '製品', reading: 'せいひん', meaning: 'product', partOfSpeech: 'noun' },
    { writing: '材料', reading: 'ざいりょう', meaning: 'material, ingredient', partOfSpeech: 'noun' },
    { writing: '道具', reading: 'どうぐ', meaning: 'tool', partOfSpeech: 'noun' },
    { writing: '機械', reading: 'きかい', meaning: 'machine', partOfSpeech: 'noun' },
    { writing: 'ゴミ', reading: 'ゴミ', meaning: 'garbage, trash', partOfSpeech: 'noun' },

    // ==================== い-Adjectives ====================
    { writing: '浅い', reading: 'あさい', meaning: 'shallow', partOfSpeech: 'i-adjective' },
    { writing: '深い', reading: 'ふかい', meaning: 'deep', partOfSpeech: 'i-adjective' },
    { writing: '厚い', reading: 'あつい', meaning: 'thick', partOfSpeech: 'i-adjective' },
    { writing: '薄い', reading: 'うすい', meaning: 'thin, light (color)', partOfSpeech: 'i-adjective' },
    { writing: '固い', reading: 'かたい', meaning: 'hard, stiff', partOfSpeech: 'i-adjective' },
    { writing: '柔らかい', reading: 'やわらかい', meaning: 'soft', partOfSpeech: 'i-adjective' },
    { writing: '細い', reading: 'ほそい', meaning: 'thin, narrow', partOfSpeech: 'i-adjective' },
    { writing: '太い', reading: 'ふとい', meaning: 'thick, fat', partOfSpeech: 'i-adjective' },
    { writing: '丸い', reading: 'まるい', meaning: 'round', partOfSpeech: 'i-adjective' },
    { writing: '四角い', reading: 'しかくい', meaning: 'square', partOfSpeech: 'i-adjective' },
    { writing: '珍しい', reading: 'めずらしい', meaning: 'rare, unusual', partOfSpeech: 'i-adjective' },
    { writing: '正しい', reading: 'ただしい', meaning: 'correct, right', partOfSpeech: 'i-adjective' },
    { writing: '悲しい', reading: 'かなしい', meaning: 'sad', partOfSpeech: 'i-adjective' },
    { writing: '嬉しい', reading: 'うれしい', meaning: 'happy, glad', partOfSpeech: 'i-adjective' },
    { writing: '寂しい', reading: 'さびしい', meaning: 'lonely', partOfSpeech: 'i-adjective' },
    { writing: '恥ずかしい', reading: 'はずかしい', meaning: 'embarrassing, shy', partOfSpeech: 'i-adjective' },
    { writing: '羨ましい', reading: 'うらやましい', meaning: 'envious', partOfSpeech: 'i-adjective' },
    { writing: '眠い', reading: 'ねむい', meaning: 'sleepy', partOfSpeech: 'i-adjective' },
    { writing: '痛い', reading: 'いたい', meaning: 'painful', partOfSpeech: 'i-adjective' },
    { writing: '痒い', reading: 'かゆい', meaning: 'itchy', partOfSpeech: 'i-adjective' },
    { writing: '気持ち悪い', reading: 'きもちわるい', meaning: 'feel sick, gross', partOfSpeech: 'i-adjective' },
    { writing: '気持ちいい', reading: 'きもちいい', meaning: 'feel good', partOfSpeech: 'i-adjective' },
    { writing: '煩い', reading: 'うるさい', meaning: 'noisy, annoying', partOfSpeech: 'i-adjective' },
    { writing: '汚い', reading: 'きたない', meaning: 'dirty', partOfSpeech: 'i-adjective' },
    { writing: '素晴らしい', reading: 'すばらしい', meaning: 'wonderful', partOfSpeech: 'i-adjective' },
    { writing: '仕方がない', reading: 'しかたがない', meaning: 'cannot be helped', partOfSpeech: 'expression' },

    // ==================== な-Adjectives ====================
    { writing: '大切', reading: 'たいせつ', meaning: 'important, precious', partOfSpeech: 'na-adjective' },
    { writing: '大事', reading: 'だいじ', meaning: 'important', partOfSpeech: 'na-adjective' },
    { writing: '必要', reading: 'ひつよう', meaning: 'necessary', partOfSpeech: 'na-adjective' },
    { writing: '特別', reading: 'とくべつ', meaning: 'special', partOfSpeech: 'na-adjective' },
    { writing: '普通', reading: 'ふつう', meaning: 'ordinary, normal', partOfSpeech: 'na-adjective' },
    { writing: '複雑', reading: 'ふくざつ', meaning: 'complicated', partOfSpeech: 'na-adjective' },
    { writing: '簡単', reading: 'かんたん', meaning: 'simple, easy', partOfSpeech: 'na-adjective' },
    { writing: '安全', reading: 'あんぜん', meaning: 'safe', partOfSpeech: 'na-adjective' },
    { writing: '危険', reading: 'きけん', meaning: 'dangerous', partOfSpeech: 'na-adjective' },
    { writing: '不便', reading: 'ふべん', meaning: 'inconvenient', partOfSpeech: 'na-adjective' },
    { writing: '便利', reading: 'べんり', meaning: 'convenient', partOfSpeech: 'na-adjective' },
    { writing: '丁寧', reading: 'ていねい', meaning: 'polite, careful', partOfSpeech: 'na-adjective' },
    { writing: '親切', reading: 'しんせつ', meaning: 'kind', partOfSpeech: 'na-adjective' },
    { writing: '熱心', reading: 'ねっしん', meaning: 'enthusiastic', partOfSpeech: 'na-adjective' },
    { writing: '真面目', reading: 'まじめ', meaning: 'serious, diligent', partOfSpeech: 'na-adjective' },
    { writing: '適当', reading: 'てきとう', meaning: 'appropriate, random', partOfSpeech: 'na-adjective' },
    { writing: '正確', reading: 'せいかく', meaning: 'accurate', partOfSpeech: 'na-adjective' },
    { writing: '自由', reading: 'じゆう', meaning: 'free, freedom', partOfSpeech: 'na-adjective' },
    { writing: '幸せ', reading: 'しあわせ', meaning: 'happy, happiness', partOfSpeech: 'na-adjective' },
    { writing: '残念', reading: 'ざんねん', meaning: 'regrettable, unfortunate', partOfSpeech: 'na-adjective' },

    // ==================== Adverbs ====================
    { writing: 'もう', reading: 'もう', meaning: 'already, anymore', partOfSpeech: 'adverb' },
    { writing: 'まだ', reading: 'まだ', meaning: 'still, not yet', partOfSpeech: 'adverb' },
    { writing: 'もうすぐ', reading: 'もうすぐ', meaning: 'very soon', partOfSpeech: 'adverb' },
    { writing: '必ず', reading: 'かならず', meaning: 'certainly, always', partOfSpeech: 'adverb' },
    { writing: 'きっと', reading: 'きっと', meaning: 'surely, certainly', partOfSpeech: 'adverb' },
    { writing: 'たぶん', reading: 'たぶん', meaning: 'probably', partOfSpeech: 'adverb' },
    { writing: 'もしかしたら', reading: 'もしかしたら', meaning: 'perhaps, maybe', partOfSpeech: 'adverb' },
    { writing: '絶対に', reading: 'ぜったいに', meaning: 'absolutely', partOfSpeech: 'adverb' },
    { writing: '全然', reading: 'ぜんぜん', meaning: 'not at all', partOfSpeech: 'adverb' },
    { writing: '全部', reading: 'ぜんぶ', meaning: 'all, everything', partOfSpeech: 'noun' },
    { writing: 'ほとんど', reading: 'ほとんど', meaning: 'almost, mostly', partOfSpeech: 'adverb' },
    { writing: '特に', reading: 'とくに', meaning: 'especially', partOfSpeech: 'adverb' },
    { writing: '実は', reading: 'じつは', meaning: 'actually, in fact', partOfSpeech: 'adverb' },
    { writing: 'やはり', reading: 'やはり', meaning: 'as expected, after all', partOfSpeech: 'adverb' },
    { writing: 'やっぱり', reading: 'やっぱり', meaning: 'as expected (casual)', partOfSpeech: 'adverb' },
    { writing: 'なかなか', reading: 'なかなか', meaning: 'quite, rather, not easily', partOfSpeech: 'adverb' },
    { writing: 'だんだん', reading: 'だんだん', meaning: 'gradually', partOfSpeech: 'adverb' },
    { writing: 'どんどん', reading: 'どんどん', meaning: 'rapidly, steadily', partOfSpeech: 'adverb' },
    { writing: 'しばらく', reading: 'しばらく', meaning: 'for a while', partOfSpeech: 'adverb' },
    { writing: 'すぐに', reading: 'すぐに', meaning: 'immediately', partOfSpeech: 'adverb' },
    { writing: '初めて', reading: 'はじめて', meaning: 'for the first time', partOfSpeech: 'adverb' },
    { writing: 'できるだけ', reading: 'できるだけ', meaning: 'as much as possible', partOfSpeech: 'expression' },
    { writing: 'なるべく', reading: 'なるべく', meaning: 'as much as possible', partOfSpeech: 'adverb' },

    // ==================== Expressions ====================
    { writing: 'お疲れ様', reading: 'おつかれさま', meaning: 'thank you for your hard work', partOfSpeech: 'expression' },
    { writing: 'ご苦労様', reading: 'ごくろうさま', meaning: 'thank you for your trouble', partOfSpeech: 'expression' },
    { writing: 'いらっしゃいませ', reading: 'いらっしゃいませ', meaning: 'welcome (to a store)', partOfSpeech: 'expression' },
    { writing: 'お待たせしました', reading: 'おまたせしました', meaning: 'sorry for the wait', partOfSpeech: 'expression' },
    { writing: 'お先に失礼します', reading: 'おさきにしつれいします', meaning: 'excuse me for leaving first', partOfSpeech: 'expression' },
    { writing: 'どうぞよろしく', reading: 'どうぞよろしく', meaning: 'pleased to meet you', partOfSpeech: 'expression' },
    { writing: 'よろしくお願いします', reading: 'よろしくおねがいします', meaning: 'please take care of it', partOfSpeech: 'expression' },
    { writing: 'お元気で', reading: 'おげんきで', meaning: 'take care', partOfSpeech: 'expression' },
    { writing: 'ご馳走様', reading: 'ごちそうさま', meaning: 'thank you for the meal', partOfSpeech: 'expression' },
    { writing: 'いただきます', reading: 'いただきます', meaning: 'thank you for the food (before eating)', partOfSpeech: 'expression' },
    { writing: 'お大事に', reading: 'おだいじに', meaning: 'take care of yourself', partOfSpeech: 'expression' },
    { writing: 'おかげで', reading: 'おかげで', meaning: 'thanks to', partOfSpeech: 'expression' },
    { writing: 'せっかく', reading: 'せっかく', meaning: 'with great effort', partOfSpeech: 'adverb' },
];
