/**
 * N5 Vocabulary data part 1 - Basic words (200 words)
 */

export const n5VocabularyData = [
    // Greetings and Basic Expressions
    { writing: 'おはよう', reading: 'おはよう', meaning: 'good morning (informal)', partOfSpeech: 'expression' },
    { writing: 'おはようございます', reading: 'おはようございます', meaning: 'good morning (polite)', partOfSpeech: 'expression' },
    { writing: 'こんにちは', reading: 'こんにちは', meaning: 'hello; good afternoon', partOfSpeech: 'expression' },
    { writing: 'こんばんは', reading: 'こんばんは', meaning: 'good evening', partOfSpeech: 'expression' },
    { writing: 'さようなら', reading: 'さようなら', meaning: 'goodbye', partOfSpeech: 'expression' },
    { writing: 'おやすみなさい', reading: 'おやすみなさい', meaning: 'good night', partOfSpeech: 'expression' },
    { writing: 'ありがとう', reading: 'ありがとう', meaning: 'thank you (informal)', partOfSpeech: 'expression' },
    { writing: 'ありがとうございます', reading: 'ありがとうございます', meaning: 'thank you (polite)', partOfSpeech: 'expression' },
    { writing: 'すみません', reading: 'すみません', meaning: 'excuse me; sorry', partOfSpeech: 'expression' },
    { writing: 'ごめんなさい', reading: 'ごめんなさい', meaning: 'I\'m sorry', partOfSpeech: 'expression' },
    { writing: 'はい', reading: 'はい', meaning: 'yes', partOfSpeech: 'expression' },
    { writing: 'いいえ', reading: 'いいえ', meaning: 'no', partOfSpeech: 'expression' },
    { writing: 'どうぞ', reading: 'どうぞ', meaning: 'please; go ahead', partOfSpeech: 'expression' },
    { writing: 'どうも', reading: 'どうも', meaning: 'thanks; very much', partOfSpeech: 'expression' },

    // Pronouns
    { writing: '私', reading: 'わたし', meaning: 'I; me', partOfSpeech: 'pronoun' },
    { writing: '僕', reading: 'ぼく', meaning: 'I; me (male)', partOfSpeech: 'pronoun' },
    { writing: 'あなた', reading: 'あなた', meaning: 'you', partOfSpeech: 'pronoun' },
    { writing: '彼', reading: 'かれ', meaning: 'he; him; boyfriend', partOfSpeech: 'pronoun' },
    { writing: '彼女', reading: 'かのじょ', meaning: 'she; her; girlfriend', partOfSpeech: 'pronoun' },
    { writing: '私達', reading: 'わたしたち', meaning: 'we; us', partOfSpeech: 'pronoun' },
    { writing: 'みんな', reading: 'みんな', meaning: 'everyone; everybody', partOfSpeech: 'pronoun' },

    // Numbers
    { writing: '一', reading: 'いち', meaning: 'one', partOfSpeech: 'number' },
    { writing: '二', reading: 'に', meaning: 'two', partOfSpeech: 'number' },
    { writing: '三', reading: 'さん', meaning: 'three', partOfSpeech: 'number' },
    { writing: '四', reading: 'よん', meaning: 'four', partOfSpeech: 'number' },
    { writing: '五', reading: 'ご', meaning: 'five', partOfSpeech: 'number' },
    { writing: '六', reading: 'ろく', meaning: 'six', partOfSpeech: 'number' },
    { writing: '七', reading: 'なな', meaning: 'seven', partOfSpeech: 'number' },
    { writing: '八', reading: 'はち', meaning: 'eight', partOfSpeech: 'number' },
    { writing: '九', reading: 'きゅう', meaning: 'nine', partOfSpeech: 'number' },
    { writing: '十', reading: 'じゅう', meaning: 'ten', partOfSpeech: 'number' },
    { writing: '百', reading: 'ひゃく', meaning: 'hundred', partOfSpeech: 'number' },
    { writing: '千', reading: 'せん', meaning: 'thousand', partOfSpeech: 'number' },
    { writing: '万', reading: 'まん', meaning: 'ten thousand', partOfSpeech: 'number' },

    // Time Words
    { writing: '今日', reading: 'きょう', meaning: 'today', partOfSpeech: 'noun' },
    { writing: '明日', reading: 'あした', meaning: 'tomorrow', partOfSpeech: 'noun' },
    { writing: '昨日', reading: 'きのう', meaning: 'yesterday', partOfSpeech: 'noun' },
    { writing: '今', reading: 'いま', meaning: 'now', partOfSpeech: 'noun' },
    { writing: '朝', reading: 'あさ', meaning: 'morning', partOfSpeech: 'noun' },
    { writing: '昼', reading: 'ひる', meaning: 'noon; lunch', partOfSpeech: 'noun' },
    { writing: '夜', reading: 'よる', meaning: 'night; evening', partOfSpeech: 'noun' },
    { writing: '午前', reading: 'ごぜん', meaning: 'morning; AM', partOfSpeech: 'noun' },
    { writing: '午後', reading: 'ごご', meaning: 'afternoon; PM', partOfSpeech: 'noun' },
    { writing: '毎日', reading: 'まいにち', meaning: 'every day', partOfSpeech: 'noun' },
    { writing: '毎週', reading: 'まいしゅう', meaning: 'every week', partOfSpeech: 'noun' },
    { writing: '毎月', reading: 'まいつき', meaning: 'every month', partOfSpeech: 'noun' },
    { writing: '毎年', reading: 'まいとし', meaning: 'every year', partOfSpeech: 'noun' },
    { writing: '先週', reading: 'せんしゅう', meaning: 'last week', partOfSpeech: 'noun' },
    { writing: '今週', reading: 'こんしゅう', meaning: 'this week', partOfSpeech: 'noun' },
    { writing: '来週', reading: 'らいしゅう', meaning: 'next week', partOfSpeech: 'noun' },
    { writing: '時間', reading: 'じかん', meaning: 'time; hour', partOfSpeech: 'noun' },

    // Days of the Week
    { writing: '月曜日', reading: 'げつようび', meaning: 'Monday', partOfSpeech: 'noun' },
    { writing: '火曜日', reading: 'かようび', meaning: 'Tuesday', partOfSpeech: 'noun' },
    { writing: '水曜日', reading: 'すいようび', meaning: 'Wednesday', partOfSpeech: 'noun' },
    { writing: '木曜日', reading: 'もくようび', meaning: 'Thursday', partOfSpeech: 'noun' },
    { writing: '金曜日', reading: 'きんようび', meaning: 'Friday', partOfSpeech: 'noun' },
    { writing: '土曜日', reading: 'どようび', meaning: 'Saturday', partOfSpeech: 'noun' },
    { writing: '日曜日', reading: 'にちようび', meaning: 'Sunday', partOfSpeech: 'noun' },

    // People
    { writing: '人', reading: 'ひと', meaning: 'person', partOfSpeech: 'noun' },
    { writing: '男', reading: 'おとこ', meaning: 'man; male', partOfSpeech: 'noun' },
    { writing: '女', reading: 'おんな', meaning: 'woman; female', partOfSpeech: 'noun' },
    { writing: '子供', reading: 'こども', meaning: 'child', partOfSpeech: 'noun' },
    { writing: '学生', reading: 'がくせい', meaning: 'student', partOfSpeech: 'noun' },
    { writing: '先生', reading: 'せんせい', meaning: 'teacher', partOfSpeech: 'noun' },
    { writing: '友達', reading: 'ともだち', meaning: 'friend', partOfSpeech: 'noun' },
    { writing: '家族', reading: 'かぞく', meaning: 'family', partOfSpeech: 'noun' },
    { writing: '父', reading: 'ちち', meaning: 'father (humble)', partOfSpeech: 'noun' },
    { writing: '母', reading: 'はは', meaning: 'mother (humble)', partOfSpeech: 'noun' },
    { writing: 'お父さん', reading: 'おとうさん', meaning: 'father (polite)', partOfSpeech: 'noun' },
    { writing: 'お母さん', reading: 'おかあさん', meaning: 'mother (polite)', partOfSpeech: 'noun' },
    { writing: '兄', reading: 'あに', meaning: 'older brother (humble)', partOfSpeech: 'noun' },
    { writing: '姉', reading: 'あね', meaning: 'older sister (humble)', partOfSpeech: 'noun' },
    { writing: '弟', reading: 'おとうと', meaning: 'younger brother', partOfSpeech: 'noun' },
    { writing: '妹', reading: 'いもうと', meaning: 'younger sister', partOfSpeech: 'noun' },

    // Places
    { writing: '家', reading: 'いえ', meaning: 'house; home', partOfSpeech: 'noun' },
    { writing: '部屋', reading: 'へや', meaning: 'room', partOfSpeech: 'noun' },
    { writing: '学校', reading: 'がっこう', meaning: 'school', partOfSpeech: 'noun' },
    { writing: '大学', reading: 'だいがく', meaning: 'university', partOfSpeech: 'noun' },
    { writing: '会社', reading: 'かいしゃ', meaning: 'company', partOfSpeech: 'noun' },
    { writing: '病院', reading: 'びょういん', meaning: 'hospital', partOfSpeech: 'noun' },
    { writing: '銀行', reading: 'ぎんこう', meaning: 'bank', partOfSpeech: 'noun' },
    { writing: '郵便局', reading: 'ゆうびんきょく', meaning: 'post office', partOfSpeech: 'noun' },
    { writing: '駅', reading: 'えき', meaning: 'train station', partOfSpeech: 'noun' },
    { writing: '店', reading: 'みせ', meaning: 'store; shop', partOfSpeech: 'noun' },
    { writing: 'レストラン', reading: 'レストラン', meaning: 'restaurant', partOfSpeech: 'noun' },
    { writing: 'ホテル', reading: 'ホテル', meaning: 'hotel', partOfSpeech: 'noun' },
    { writing: '図書館', reading: 'としょかん', meaning: 'library', partOfSpeech: 'noun' },
    { writing: '公園', reading: 'こうえん', meaning: 'park', partOfSpeech: 'noun' },
    { writing: '空港', reading: 'くうこう', meaning: 'airport', partOfSpeech: 'noun' },

    // Food and Drink
    { writing: '食べ物', reading: 'たべもの', meaning: 'food', partOfSpeech: 'noun' },
    { writing: '飲み物', reading: 'のみもの', meaning: 'drink', partOfSpeech: 'noun' },
    { writing: 'ご飯', reading: 'ごはん', meaning: 'rice; meal', partOfSpeech: 'noun' },
    { writing: 'パン', reading: 'パン', meaning: 'bread', partOfSpeech: 'noun' },
    { writing: '肉', reading: 'にく', meaning: 'meat', partOfSpeech: 'noun' },
    { writing: '魚', reading: 'さかな', meaning: 'fish', partOfSpeech: 'noun' },
    { writing: '野菜', reading: 'やさい', meaning: 'vegetable', partOfSpeech: 'noun' },
    { writing: '果物', reading: 'くだもの', meaning: 'fruit', partOfSpeech: 'noun' },
    { writing: '卵', reading: 'たまご', meaning: 'egg', partOfSpeech: 'noun' },
    { writing: '水', reading: 'みず', meaning: 'water', partOfSpeech: 'noun' },
    { writing: 'お茶', reading: 'おちゃ', meaning: 'tea', partOfSpeech: 'noun' },
    { writing: 'コーヒー', reading: 'コーヒー', meaning: 'coffee', partOfSpeech: 'noun' },
    { writing: '牛乳', reading: 'ぎゅうにゅう', meaning: 'milk', partOfSpeech: 'noun' },
    { writing: 'ビール', reading: 'ビール', meaning: 'beer', partOfSpeech: 'noun' },
    { writing: '朝ご飯', reading: 'あさごはん', meaning: 'breakfast', partOfSpeech: 'noun' },
    { writing: '昼ご飯', reading: 'ひるごはん', meaning: 'lunch', partOfSpeech: 'noun' },
    { writing: '晩ご飯', reading: 'ばんごはん', meaning: 'dinner', partOfSpeech: 'noun' },

    // Objects
    { writing: '本', reading: 'ほん', meaning: 'book', partOfSpeech: 'noun' },
    { writing: 'ノート', reading: 'ノート', meaning: 'notebook', partOfSpeech: 'noun' },
    { writing: '鉛筆', reading: 'えんぴつ', meaning: 'pencil', partOfSpeech: 'noun' },
    { writing: 'ペン', reading: 'ペン', meaning: 'pen', partOfSpeech: 'noun' },
    { writing: '机', reading: 'つくえ', meaning: 'desk', partOfSpeech: 'noun' },
    { writing: '椅子', reading: 'いす', meaning: 'chair', partOfSpeech: 'noun' },
    { writing: '電話', reading: 'でんわ', meaning: 'telephone', partOfSpeech: 'noun' },
    { writing: '時計', reading: 'とけい', meaning: 'clock; watch', partOfSpeech: 'noun' },
    { writing: '傘', reading: 'かさ', meaning: 'umbrella', partOfSpeech: 'noun' },
    { writing: '鍵', reading: 'かぎ', meaning: 'key', partOfSpeech: 'noun' },
    { writing: '財布', reading: 'さいふ', meaning: 'wallet', partOfSpeech: 'noun' },
    { writing: 'かばん', reading: 'かばん', meaning: 'bag', partOfSpeech: 'noun' },
    { writing: '靴', reading: 'くつ', meaning: 'shoes', partOfSpeech: 'noun' },
    { writing: '服', reading: 'ふく', meaning: 'clothes', partOfSpeech: 'noun' },
    { writing: '写真', reading: 'しゃしん', meaning: 'photograph', partOfSpeech: 'noun' },

    // Common Verbs (ます form)
    { writing: '食べる', reading: 'たべる', meaning: 'to eat', partOfSpeech: 'verb' },
    { writing: '飲む', reading: 'のむ', meaning: 'to drink', partOfSpeech: 'verb' },
    { writing: '行く', reading: 'いく', meaning: 'to go', partOfSpeech: 'verb' },
    { writing: '来る', reading: 'くる', meaning: 'to come', partOfSpeech: 'verb' },
    { writing: '帰る', reading: 'かえる', meaning: 'to return home', partOfSpeech: 'verb' },
    { writing: '見る', reading: 'みる', meaning: 'to see; to look', partOfSpeech: 'verb' },
    { writing: '聞く', reading: 'きく', meaning: 'to hear; to listen; to ask', partOfSpeech: 'verb' },
    { writing: '話す', reading: 'はなす', meaning: 'to speak; to talk', partOfSpeech: 'verb' },
    { writing: '読む', reading: 'よむ', meaning: 'to read', partOfSpeech: 'verb' },
    { writing: '書く', reading: 'かく', meaning: 'to write', partOfSpeech: 'verb' },
    { writing: '買う', reading: 'かう', meaning: 'to buy', partOfSpeech: 'verb' },
    { writing: '待つ', reading: 'まつ', meaning: 'to wait', partOfSpeech: 'verb' },
    { writing: '会う', reading: 'あう', meaning: 'to meet', partOfSpeech: 'verb' },
    { writing: 'ある', reading: 'ある', meaning: 'to exist (inanimate)', partOfSpeech: 'verb' },
    { writing: 'いる', reading: 'いる', meaning: 'to exist (animate)', partOfSpeech: 'verb' },
    { writing: 'する', reading: 'する', meaning: 'to do', partOfSpeech: 'verb' },
    { writing: '勉強する', reading: 'べんきょうする', meaning: 'to study', partOfSpeech: 'verb' },
    { writing: '仕事する', reading: 'しごとする', meaning: 'to work', partOfSpeech: 'verb' },
    { writing: '起きる', reading: 'おきる', meaning: 'to wake up; to get up', partOfSpeech: 'verb' },
    { writing: '寝る', reading: 'ねる', meaning: 'to sleep; to go to bed', partOfSpeech: 'verb' },
    { writing: '入る', reading: 'はいる', meaning: 'to enter', partOfSpeech: 'verb' },
    { writing: '出る', reading: 'でる', meaning: 'to exit; to leave', partOfSpeech: 'verb' },
    { writing: '休む', reading: 'やすむ', meaning: 'to rest; to take a day off', partOfSpeech: 'verb' },
    { writing: '立つ', reading: 'たつ', meaning: 'to stand', partOfSpeech: 'verb' },
    { writing: '座る', reading: 'すわる', meaning: 'to sit', partOfSpeech: 'verb' },
    { writing: '歩く', reading: 'あるく', meaning: 'to walk', partOfSpeech: 'verb' },
    { writing: '走る', reading: 'はしる', meaning: 'to run', partOfSpeech: 'verb' },
    { writing: '泳ぐ', reading: 'およぐ', meaning: 'to swim', partOfSpeech: 'verb' },
    { writing: '遊ぶ', reading: 'あそぶ', meaning: 'to play; to have fun', partOfSpeech: 'verb' },
    { writing: '使う', reading: 'つかう', meaning: 'to use', partOfSpeech: 'verb' },

    // い-Adjectives
    { writing: '大きい', reading: 'おおきい', meaning: 'big; large', partOfSpeech: 'i-adjective' },
    { writing: '小さい', reading: 'ちいさい', meaning: 'small; little', partOfSpeech: 'i-adjective' },
    { writing: '新しい', reading: 'あたらしい', meaning: 'new', partOfSpeech: 'i-adjective' },
    { writing: '古い', reading: 'ふるい', meaning: 'old (things)', partOfSpeech: 'i-adjective' },
    { writing: '高い', reading: 'たかい', meaning: 'high; tall; expensive', partOfSpeech: 'i-adjective' },
    { writing: '安い', reading: 'やすい', meaning: 'cheap; inexpensive', partOfSpeech: 'i-adjective' },
    { writing: '良い', reading: 'いい', meaning: 'good', partOfSpeech: 'i-adjective' },
    { writing: '悪い', reading: 'わるい', meaning: 'bad', partOfSpeech: 'i-adjective' },
    { writing: '長い', reading: 'ながい', meaning: 'long', partOfSpeech: 'i-adjective' },
    { writing: '短い', reading: 'みじかい', meaning: 'short', partOfSpeech: 'i-adjective' },
    { writing: '熱い', reading: 'あつい', meaning: 'hot (things)', partOfSpeech: 'i-adjective' },
    { writing: '寒い', reading: 'さむい', meaning: 'cold (weather)', partOfSpeech: 'i-adjective' },
    { writing: '冷たい', reading: 'つめたい', meaning: 'cold (things)', partOfSpeech: 'i-adjective' },
    { writing: '暑い', reading: 'あつい', meaning: 'hot (weather)', partOfSpeech: 'i-adjective' },
    { writing: '面白い', reading: 'おもしろい', meaning: 'interesting; funny', partOfSpeech: 'i-adjective' },
    { writing: '楽しい', reading: 'たのしい', meaning: 'fun; enjoyable', partOfSpeech: 'i-adjective' },
    { writing: '難しい', reading: 'むずかしい', meaning: 'difficult', partOfSpeech: 'i-adjective' },
    { writing: '易しい', reading: 'やさしい', meaning: 'easy; simple', partOfSpeech: 'i-adjective' },
    { writing: '忙しい', reading: 'いそがしい', meaning: 'busy', partOfSpeech: 'i-adjective' },
    { writing: '美味しい', reading: 'おいしい', meaning: 'delicious', partOfSpeech: 'i-adjective' },
    { writing: '近い', reading: 'ちかい', meaning: 'near; close', partOfSpeech: 'i-adjective' },
    { writing: '遠い', reading: 'とおい', meaning: 'far', partOfSpeech: 'i-adjective' },
    { writing: '早い', reading: 'はやい', meaning: 'early; fast', partOfSpeech: 'i-adjective' },
    { writing: '遅い', reading: 'おそい', meaning: 'late; slow', partOfSpeech: 'i-adjective' },
    { writing: '多い', reading: 'おおい', meaning: 'many; much', partOfSpeech: 'i-adjective' },
    { writing: '少ない', reading: 'すくない', meaning: 'few; little', partOfSpeech: 'i-adjective' },

    // な-Adjectives
    { writing: '元気', reading: 'げんき', meaning: 'healthy; energetic', partOfSpeech: 'na-adjective' },
    { writing: '好き', reading: 'すき', meaning: 'like; love', partOfSpeech: 'na-adjective' },
    { writing: '嫌い', reading: 'きらい', meaning: 'dislike; hate', partOfSpeech: 'na-adjective' },
    { writing: '静か', reading: 'しずか', meaning: 'quiet', partOfSpeech: 'na-adjective' },
    { writing: '賑やか', reading: 'にぎやか', meaning: 'lively', partOfSpeech: 'na-adjective' },
    { writing: '有名', reading: 'ゆうめい', meaning: 'famous', partOfSpeech: 'na-adjective' },
    { writing: '便利', reading: 'べんり', meaning: 'convenient', partOfSpeech: 'na-adjective' },
    { writing: '大丈夫', reading: 'だいじょうぶ', meaning: 'okay; all right', partOfSpeech: 'na-adjective' },
    { writing: '大切', reading: 'たいせつ', meaning: 'important', partOfSpeech: 'na-adjective' },
    { writing: '綺麗', reading: 'きれい', meaning: 'beautiful; clean', partOfSpeech: 'na-adjective' },
    { writing: '暇', reading: 'ひま', meaning: 'free (time)', partOfSpeech: 'na-adjective' },
    { writing: '親切', reading: 'しんせつ', meaning: 'kind', partOfSpeech: 'na-adjective' },
    { writing: '上手', reading: 'じょうず', meaning: 'skillful; good at', partOfSpeech: 'na-adjective' },
    { writing: '下手', reading: 'へた', meaning: 'unskillful; bad at', partOfSpeech: 'na-adjective' },
    { writing: '簡単', reading: 'かんたん', meaning: 'easy; simple', partOfSpeech: 'na-adjective' },
];
